FROM registry.access.redhat.com/ubi9/go-toolset@sha256:6402ad7886fb3bdaa950c89bdf338f8dbedde54c16bddb1157ebb8691b2def50 as builder

USER root

COPY . .

RUN go build -buildvcs=false .

FROM registry.access.redhat.com/ubi9-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc

LABEL org.opencontainers.image.authors = "Adrian Riobo"

COPY --from=builder /opt/app-root/src/seminario /usr/local/bin/

ENTRYPOINT ["seminario"]